name: deploy
on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: dev
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - sandpit
          - dev
          - uat
          - test
          - prod

jobs:
  deploy-stack:
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: npm ci
        working-directory: '.'
        run: npm ci #--userconfig=./.npmrc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: npm run build
        working-directory: '.'
        run: npm run build

      - name: install cdk
        working-directory: '.'
        run: | 
          npm i -g
          source ~/.bashrc 

      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'synth'
          cdk_args: '--debug'
          working_dir: '.'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ENV_HOME: 'env'
          ENV_NAME: ${{inputs.environment}}
          AWS_DEFAULT_REGION: ap-southeast-2
          AWS_DEFAULT_OUTPUT: json
